packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1

overrides:
  next: ^16.2.3
  esbuild: ^0.25.0
  srvx: ^0.11.13
  '@hono/node-server': ^1.19.13
  postcss: ^8.5.10
  defu: ^6.1.5
  picomatch: ^4.0.4
  drizzle-orm: ^0.45.2
  h3: ^2.0.1-rc.18
