name: Scrape Mercari

on:
  schedule:
    # Run every day at 4 AM UTC (This is 12 PM UTC+8)
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    # This job will only run on the main branch for scheduled events or when manually triggered
    if: ${{ github.event_name != 'schedule' || github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate prisma client
        run: pnpm run generate

      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(pnpm list --filter scraper playwright --json | jq -r '.[0].devDependencies.playwright.version')" >> $GITHUB_OUTPUT

      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v5
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps chromium
        working-directory: apps/scraper

      - name: Install Playwright Dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps chromium
        working-directory: apps/scraper

      - name: Run scraper
        run: pnpm run scraper
        working-directory: apps/scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          WEB_APP_URL: ${{ secrets.WEB_APP_URL }}

      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: apps/scraper/playwright-report/
          retention-days: 7
