name: Scrape Mercari

on:
  schedule:
    # Run every day at 4 AM UTC (This is 12 AM UTC+8)
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    # This job will only run on the main branch for scheduled events or when manually triggered
    if: ${{ github.event_name != 'schedule' || github.ref == 'refs/heads/main' }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Generate prisma client
        run: npm run preinstall
      - name: Run Playwright tests
        run: npm run test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: services/scraper/playwright-report/
          retention-days: 7
