name: Scrape Mercari

on:
  schedule:
    # Run every day at 4 AM UTC (This is 12 PM UTC+8)
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    # This job will only run on the main branch for scheduled events or when manually triggered
    if: ${{ github.event_name != 'schedule' || github.ref == 'refs/heads/main' }}
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Generate prisma client
        run: pnpm run generate
      - name: Install Playwright Browsers
        run: cd apps/scraper && pnpm exec playwright install --with-deps chromium
      - name: Run scraper
        run: pnpm run scraper
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: apps/scraper/playwright-report/
          retention-days: 7
